language: node_js
node_js:
  - "10"
  - "11"
sudo: false
cache:
  directories:
  - node_modules # NPM packages
install:
  - yarn install
  - yarn build
  - yarn lint
deploy:
  provider: npm
  email: abs-saas@sparwelt.de
  api_key: $NPM_TOKEN
  on:
    all_branches: true