language: node_js
node_js:
  - "7"
sudo: false
cache:
  directories:
  - node_modules # NPM packages
install:
  - npm install
  - npm run build
  - npm run lint
deploy:
  provider: npm
  email: abs-saas@sparwelt.de
  api_key: $NPM_TOKEN
  on:
    all_branches: true